services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    network_mode: "host"
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: "postgresql+psycopg2://cookuser:newpassword@localhost:5432/cookapp_db"
      FRONTEND_ORIGIN: "http://localhost:5173"
      JWT_SECRET: "V3RY_SECRET_KEY_CHANGE_IN_PROD"
      ACCESS_TOKEN_EXPIRE_MINUTES: 15
      REFERRER_POLICY: "no-referrer"
    volumes:
      - .:/backend/app
    command: ["uv", "run", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    network_mode: "host"
    restart: unless-stopped
    ports:
      - "80:5173"
    environment:
      VITE_API_BASE: "http://localhost:8000"
    volumes:
      - ./frontend:/app
    command: ["nginx", "-g", "daemon off;"]