"""add instruction_link to recipe

Revision ID: 61ffa56c8dfc
Revises: 2fdc82b10c29
Create Date: 2025-08-08 17:52:15.254788

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61ffa56c8dfc'
down_revision: Union[str, Sequence[str], None] = '2fdc82b10c29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('instruction_link', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipes', 'instruction_link')
    # ### end Alembic commands ###
